dist: trusty
sudo: required
language: c

os:
    - linux

compiler:
    - gcc
    - clang

env:
    - TARGET_CPU=amd64
    - TARGET_CPU=x86

script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
    - ctest --output-on-failure
