Import('env')

env['CPPPATH'] = ['../include']
env['LIBPATH'] = ['../src']
env['LIBS'] = ['graph7-%s' % env['VERSION']]
env['CFLAGS'] = ['-g']

env.Program(target='example1.exe', source=['example1.c'])
