Import('env')

sphinx_source = [
    'doxyfile',
    'conf.py',
    'index.rst',
    'getting-started/index.rst',
    'api-reference/index.rst',
#    'api-reference/graph7/index.rst',
]

env.Command(source='doxyfile', target='xml/index.xml', action='doxygen $SOURCE')
env.Command(source=sphinx_source, target='index.html', action='sphinx-build docs build/docs')
