Import('env')

env['LIBS'] = ['m']
env['CFLAGS'] = ['-O2']

source = [
    'graph7.c',
    'graph6.c',
    'utils.c',
    'bitstream.c',
]

env.StaticLibrary(target='graph7-{version}'.format(version=env['VERSION']), source=source)
env.SharedLibrary(target = 'graph7', source=source)
