Import('env')

env['CPPPATH'] = ['../include']
env['LIBS'] = ['m']
#env['CFLAGS'] = ['-O2']

source = [
    'graph7.c',
    'csvparser.c',
]

env.StaticLibrary(target='graph7-%s' % env['VERSION'], source=source)
#env.SharedLibrary(target = 'graph7', SHLIBVERSION = env['VERSION', source = ['graph7.c'])
